# Generated by Django 3.2.6 on 2021-08-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_auto_20210811_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='release_date',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
